### ISSUE TITLE
你那一堆插件都用不了你发版干嘛?

### ISSUE THREAD

**Issue by lumia1998** [WhitePaper233/asuna-plugin-bili-parser#1]

**Comment by WhitePaper233** [comment]
管你吊事 逼着你用了？

**Comment by lumia1998** [comment]
那你别发啊贱不贱啊

**Comment by WhitePaper233** [comment]
> 那你别发啊贱不贱啊

嗷牛皮 npm还是koishi社区哪条规定了你不能用的插件就不能发了？为什么我自己用着没问题？为什么不想想自己有什么问题？试过版本兼容性错误没？错误报告呢？脑子有问题去医院别到我这来撒泼打滚

**Comment by WhitePaper233** [comment]
> 那你别发啊贱不贱啊

![1575e633715ef1dc9f5e4762ba03c915](https://github.com/user-attachments/assets/bf4f2513-4ab7-4cb6-9409-c783e75b34f5)
来来来告诉我不能用 那这是什么

**Comment by lumia1998** [comment]
![dbf42c39709ef945ddde5f0f7e41c54d](https://github.com/user-attachments/assets/c00b8281-54c5-40ce-aa66-f637726dec7c)
你看看你其他插件都是啥?只有一个readme和package让人怎么用?
要不是你有2个插件能用贴git地址都找不到你

**Comment by WhitePaper233** [comment]
> ![dbf42c39709ef945ddde5f0f7e41c54d](https://private-user-images.githubusercontent.com/63107956/361394718-c00b8281-54c5-40ce-aa66-f637726dec7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjY3NjUsIm5iZiI6MTcyNDY2NjQ2NSwicGF0aCI6Ii82MzEwNzk1Ni8zNjEzOTQ3MTgtYzAwYjgyODEtNTRjNS00MGNlLWFhNjYtZjYzNzcyNmRlYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEwMDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNWEyOWIyNjk3NzI4NGQxM2FmOGFlMWM2ZTBiYzRmZDViMDE1MGU1OTI4NmYwNjJlNGFmNzU5ZWRhZmY5NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e9ZriTwn8HWKuSkjvH4CB5BcJ5xxl74gJ3SbH7cwJZ0) 你看看你其他插件都是啥?只有一个readme和package让人怎么用? 要不是你有2个插件能用贴git地址都找不到你

所以就算这两个插件我发错版了还是没写完跟你有jb关系？逼着你用了？然后你还跑来一个没问题的仓库狗叫？你就不会去有问题的仓库提issue说发包有问题？知不知道基础的社区准则？你妈没教过你怎么提问题？😅不会生下来就没人教吧🤣

**Comment by lumia1998** [comment]
只有2个?傻逼东西,我妈没教过我和死妈玩意儿讲道理

**Comment by WhitePaper233** [comment]
> 只有2个?傻逼东西,我妈没教过我和死妈玩意儿讲道理

你无敌了 自己跑来别人仓库里找事 b话讲半天讲不明白 issue是让你发泄情绪拉屎的地方？不会说话我可以把你塞进你妈逼里让你重开一把的🤣🤣🤣

**Comment by WhitePaper233** [comment]
> 只有2个?傻逼东西,我妈没教过我和死妈玩意儿讲道理

再问一句，我逼你用了吗？我允许你用了吗？这么想用你咋不自己写呢？npm和koishi仓库里那么多用不了的东西你要不要一个个发issue喷一下作者啊？是吧仓库垃圾清理小能手

**Comment by WhitePaper233** [comment]
> 只有2个?傻逼东西,我妈没教过我和死妈玩意儿讲道理

鉴于你是个妹吗的股儿我就教教你怎么正确地提问：
1.发现插件用不了 去npm看源代码
2.发现没有源代码 推测可能是占坑仓库或者发包错误导致的问题
3.去github找仓库 发现仓库里有代码 基本推测是发包错误导致的问题
4.**礼貌**地提一个issue 标题说明npm仓库上的包不可用 内容给上npm的截图
5.等待我回复你的问题 帮你解决
而古儿会怎么办呢？找到一个没问题的仓库提issue 把自己当大爷摆上几个大字：你那一堆插件都用不了你发版干嘛?
